# Generated by Django 3.0.6 on 2020-12-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="snippet",
            name="tag",
            field=models.ManyToManyField(blank=True, to="app.Tag"),
        ),
    ]
